name = "wormhole"
main = "src/index.ts"
compatibility_date = "2023-09-22"

[vars]
DOMAIN = "akashrajpurohit.com"
FALLBACK_URL = "https://akashrajpurohit.com/blogs/"

[observability]
enabled = true
head_sampling_rate = 1
